language: python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
- pip install --upgrade pip setuptools wheel

install:
  - pip install .

script: python tests/test_fdl.py
